# Generated by Django 4.2.6 on 2023-12-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_team'),
        ('tasks', '0002_todoitem'),
    ]

    operations = [
    ]
