# Generated by Django 4.2.7 on 2023-11-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_task_assigned_to_task_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                max_length=50,
            ),
        ),
    ]
