# Generated by Django 4.2.6 on 2023-12-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
        ('tasks', '0003_merge_0002_task_team_0002_todoitem'),
    ]

    operations = [
    ]
