# Generated by Django 4.2.6 on 2023-12-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_merge_20231206_1411'),
        ('tasks', '0005_task_user'),
    ]

    operations = [
    ]
