# Generated by Django 4.2.6 on 2023-12-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_team_members_alter_team_name_alter_team_tasks'),
        ('tasks', '0007_task_assigned_to_task_created_by_task_description_and_more'),
    ]

    operations = [
    ]
